# Configure a base URL for the Ollama Server
quarkus.langchain4j.ollama.base-url=http://localhost:11434

# Define model ID which langchain4j will invoke on Ollama Server
quarkus.langchain4j.ollama.chat-model.model-id=gpt-oss:20b


# Define the timeout for the call
# If model takes longer than 60s to respond, the call will fail
quarkus.langchain4j.ollama.timeout=600


